apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-pv-mongo
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: free5gc-helm
    app.kubernetes.io/name: mongodb
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: free5gc-pv-mongo-unique-id
    volumeAttributes:
      server: 10.0.0.2
      share: /srv/nfs/mongodb
