apiVersion: v1
kind: PersistentVolume
metadata:
  name: free5gc-pv-cert
  labels:
    project: free5gc
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: free5gc-pv-cert-unique-id
    volumeAttributes:
      server: 10.0.0.2
      share: /srv/nfs/cert
