apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: loxilb-lb
spec:
  selector:
    matchLabels:
      app: loxilb-app
  template:
    metadata:
      name: loxilb-lb
      labels:
        app: loxilb-app
      annotations:
        k8s.v1.cni.cncf.io/networks: '[ { "name": "n2network-free5gc-helm-free5gc-amf",
          "interface": "n2", "ips": [ "10.100.51.253/24" ], "gateway": [ "10.100.51.1"
          ] }]'
    spec:
      #hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: "control-plane"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: Exists
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
      containers:
      - name: loxilb-app
        image: "ghcr.io/loxilb-io/loxilb:scp2"
        imagePullPolicy: Always
        command: [ "/root/loxilb-io/loxilb/loxilb", "--proxyonlymode" ]
        ports:
        - containerPort: 11111
        - containerPort: 31412
          hostPort: 31412
          protocol: SCTP
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "apt-get install iptables -y && iptables -t nat -A PREROUTING -p sctp -i eth0 --dport 31412 -j DNAT --to 10.100.51.253:31412"]
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-egress-service
  annotations:
    loxilb.io/egress: "yes"
    loxilb.io/probetype: "none"
spec:
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: loxilb-app
  ports:
  - name: loxilb-egress
    port: 9999
    targetPort: 9999
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: loxilb-lb-service
spec:
  clusterIP: None
  selector:
    app: loxilb-app
  ports:
  - name: loxilb-app
    port: 11111
    targetPort: 11111
    protocol: TCP
